# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

job_defaults: &job_defaults
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    resource_class: medium
    parallelism: 1

jobs:
  test:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Store gcloud creds to key file
          command: |
            echo "$GCLOUD_SERVICE_ACCOUNT" | base64 -di > ./gcloud_key_encrypted.json.gpg
            echo "$PRIVATE_GPG_PHRASE" | gpg --pinentry-mode loopback --cipher-algo AES256 \
            --passphrase-fd 0 -d ./gcloud_key_encrypted.json.gpg > ./gcloud_key.json
            export GOOGLE_APPLICATION_CREDENTIALS=./gcloud_key.json
      - run:
          name: Login to docker to pull artifact registry image
          command: |
            # Use custom docker image from artifact registry
            gcloud auth configure-docker $REGION-docker.pkg.dev
            cat ./gcloud_key.json | docker login -u _json_key --password-stdin https://$REGION-docker.pkg.dev
            docker run -d --name curation-nlp-base $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$CONTAINER_ID:1.2
      - run:
          name: Activate gcloud creds
          command: |
            gcloud auth activate-service-account --key-file=./gcloud_key.json
      - run:
          name: Running tests
          command: |
            mvn --settings .circleci/settings.xml \
              -Dtest=$(for file in $(circleci tests glob "src/test/**/**.java" | circleci tests split --split-by=timings); \
                do basename $file | sed -e "s/.java/,/"; done | tr -d '\r\n') \
              test verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/coverage-reports/jacoco/index.html

  build:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Store gcloud creds to key file
          command: |
            echo "$GCLOUD_SERVICE_ACCOUNT" | base64 -di > ./gcloud_key_encrypted.json.gpg
            echo "$PRIVATE_GPG_PHRASE" | gpg --pinentry-mode loopback --cipher-algo AES256 \
            --passphrase-fd 0 -d ./gcloud_key_encrypted.json.gpg > ./gcloud_key.json
            export GOOGLE_APPLICATION_CREDENTIALS=./gcloud_key.json
      - run:
          name: Login to docker to pull artifact registry image
          command: |
            # Use custom docker image from artifact registry
            gcloud auth configure-docker $REGION-docker.pkg.dev
            cat ./gcloud_key.json | docker login -u _json_key --password-stdin https://$REGION-docker.pkg.dev
            docker run -d --name curation-nlp-base $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$CONTAINER_ID:1.2
      - run:
          name: Activate gcloud creds
          command: |
            gcloud auth activate-service-account --key-file=./gcloud_key.json
      - run:
          name: Maven build
          command: mvn --settings .circleci/settings.xml -Dmaven.test.skip=true package
      - persist_to_workspace:
          root: ./
          paths:
            - target/

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
