# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

commands:
  build-artifacts:
    steps:
      - run:
          name: Creating Artifacts
          command: |
            mkdir /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifact-file

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    resource_class: medium
    steps:
      - build-artifacts
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  test:
    jobs:
      - build-and-test
