# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-artifacts:
    working_directory: /tmp
    steps:
      - run:
          name: Creating Artifacts
          command: |
            mkdir /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifact-file
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  sample:
    jobs:
      - build-artifacts
      - build-and-test
