# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

job_defaults: &job_defaults
    docker:
      - image: google/cloud-sdk:160.0.0
    docker_layer_caching: true
    resource_class: medium
    parallelism: 1

commands:
  setup:
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run:
          name: Store gcloud creds to key file
          command: |
            echo "$GCLOUD_SERVICE_ACCOUNT" | base64 --decode > ./gcloud_key.json
      - run:
          name: Activate gcloud creds
          command: |
            gcloud auth activate-service-account --key-file=./gcloud_key.json

jobs:
  test:
    <<: *job_defaults
    steps:
      - setup
      - run:
          name: Running tests
          command: |
            mvn -Dtest=$(for file in $(circleci tests glob "src/test/**/**.java" |
            circleci tests split --split-by=timings); \
            do basename $file | sed -e "s/.java/,/"; done |
            tr -d '\r\n') \
            -e test verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/coverage-reports/jacoco/index.html

  build:
    <<: *job_defaults
    steps:
      - setup
      - run:
          name: Maven build
          command: mvn -Dmaven.test.skip=true package
      - persist_to_workspace:
          root: ./
          paths:
            - target/

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
