# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

job_defaults: &job_defaults
    docker:
        # Use custom docker image from artifact registry
      - image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$CONTAINER_ID:1.2
        auth:
          username: _json_key_base64
          password: $GCLOUD_SERVICE_ACCOUNT
    resource_class: medium
    parallelism: 1

commands:
  setup:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ./target
      - run:
          name: Store gcloud creds to key file
          command: |
            echo "$GCLOUD_SERVICE_ACCOUNT" | base64 --decode > ./gcloud_key.json
      - run:
          name: Activate gcloud creds
          command: |
            gcloud auth activate-service-account --key-file=./gcloud_key.json

jobs:
  test:
    <<: *job_defaults
    steps:
      - setup
      - run:
          name: Running tests
          command: |
            mvn --settings .circleci/settings.xml \
              -Dtest=$(for file in $(circleci tests glob "src/test/**/**.java" | circleci tests split --split-by=timings); \
                do basename $file | sed -e "s/.java/,/"; done | tr -d '\r\n') \
              test verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/coverage-reports/jacoco/index.html

  build:
    <<: *job_defaults
    steps:
      - setup
      - run:
          name: Maven build
          command: mvn --settings .circleci/settings.xml -Dmaven.test.skip=true package
      - persist_to_workspace:
          root: ./
          paths:
            - target/

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
