steps:
  - id: "fetch mvn settings.xml and update"
    name: "gcr.io/cloud-builders/gsutil"
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        copy_cmd='gsutil cp '"$${LOCATION}"'/config/settings.xml .'
        $copy_cmd
        sed -i -e 's/CLAMP_REG_PASSWORD/'"$${CLAMP_REG_PASSWORD}"'/g' settings.xml
    secretEnv: ['LOCATION', 'CLAMP_REG_PASSWORD']
  - id: "build and deploy to dataflow"
    name: "gcr.io/cloud-builders/mvn:3.5.0-jdk-8"
    entrypoint: 'bash'
    env:
      - 'PRIVATE_CLAMP_REPO_URL=${_PRIVATE_CLAMP_REPO_URL}'
    args:
      - '-c'
      - |
        echo "Build identifier = ${BUILD_ID}_${SHORT_SHA}"
        mvn compile exec:java \
          --settings settings.xml \
          -Dexec.mainClass="org.allofus.curation.pipeline.CurationNLPMain" \
          -Dexec.args="--project=${PROJECT_ID} \
            --gcpTempLocation=$${LOCATION}/gcp_tmp \
            --stagingLocation=$${LOCATION}/staging \
            --tempLocation=$${LOCATION}/tmp \
            --runner=DataflowRunner \
            --region=${LOCATION} \
            --input=${_INPUT} \
            --output=${_OUTPUT} \
            --pipeline=${_PIPELINE} \
            --resourcesDir=$${LOCATION}/resources \
            --inputType=${_DATATYPE} \
            --outputType=${_DATATYPE} \
            --subnetwork=$${SUBNET} \
            --workerMachineType=${_WORKER_MACHINE_TYPE} \
            --diskSizeGb=${_DISK_SIZE_GB} \
            --maxNumWorkers=${_MAX_NUM_WORKERS} \
            --numberOfWorkerHarnessThreads=${_NUM_WORKER_THREADS} \
            --maxClampThreads=${_MAX_CLAMP_THREADS} \
            --maxOutputPartitionSeconds=${_MAX_OUTPUT_PARTITION_SECONDS} \
            --maxOutputBatchSize=${_MAX_OUTPUT_BATCH_SIZE} \
            --buildId=${BUILD_ID}_${SHORT_SHA} \
            --usePublicIps=false \
            --experiments=${_EXPERIMENTS} \
            ${_STREAMING}" \
          -Pdataflow-runner -P dataflow
    secretEnv: ['LOCATION', 'SUBNET']
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/dataflow-location/versions/latest
      env: 'LOCATION'
    - versionName: projects/${PROJECT_ID}/secrets/dataflow-subnet/versions/latest
      env: 'SUBNET'
    - versionName: projects/${PROJECT_ID}/secrets/artifact-reg-clamp-password/versions/latest
      env: 'CLAMP_REG_PASSWORD'
options:
    dynamic_substitutions: true
    logging: CLOUD_LOGGING_ONLY
